name: ZapMerchant
description: zap.me merchant app
version: 1.1.7+22

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # ios & android only
  shared_preferences: 0.5.6+3
  package_info: 0.4.0+16
  qrcode_reader:
    git:
      url: https://github.com/bcko/flutter_qrcode_reader.git
      ref: ff0a26b
  url_launcher: ^5.4.2 # has flutter-desktop-go native plugin for desktop
  path_provider: ^1.6.5
  
  # for desktop
  ini: ^2.0.1

  intl: ^0.15.8
  qr_flutter: 2.1.0+55
  flushbar: 1.10.0
  decimal: 0.3.3
  encrypt: ^3.2.0
  base58check: ^1.0.1
  yaml: ^2.1.16
  flutter_icons: ^1.0.0+1
  ffi: 0.1.3-dev.3
  http: ^0.12.0+2
  crypto: 2.1.3
  socket_io_client: ^0.9.7+2
  hex: ^0.1.2
  pin_code_text_field: ^1.5.1
  edit_distance: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900

  # add pubspec so we can read the version on desktop
  assets:
    - assets/
    - pubspec.yaml
    - native-libraries/windows/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
