name: Flutter iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.17.x'
        channel: 'beta'
    - name: download libzap
      run: wget https://github.com/djpnewton/libzap/releases/download/v12/ios.zip
    - name: extract libzap
      run: cd native-libraries; mkdir ios; cd ios; unzip ../../ios.zip
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build appbundle
    - name: upload appbundle
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: build/app/outputs/apk/release/app-release.apk
