# This is a basic workflow to help you get started with Actions

name: Flutter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.17.x'
        channel: 'beta'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
