name: Flutter Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.17.x'
        channel: 'beta'
    - name: install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
    - name: download libzap
      run: wget https://github.com/djpnewton/libzap/releases/download/v12/android.zip
    - name: extract libzap
      run: cd native-libraries; mkdir android; cd android; unzip ../../android.zip
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    - name: upload apk
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: build/app/outputs/apk/release/app-release.apk
